### ISSUE TITLE
Repository<T>

### ISSUE THREAD

**Issue by jovi-Li** [msotiroff/EasyDynamo#4]
how to implement a generics Repository  , like 
 public class Repository<TEntity> : IRepository<TEntity> 

DynamoDbSet can not set by myselft

**Comment by jovi-Li** [comment]
I add  this code in  DynamoContext:

 public virtual DynamoDbSet<TEntity> Set<TEntity>()
            where TEntity : class, new()
        {
            var constructor = typeof(DynamoDbSet<TEntity>)
                .GetConstructors(BindingFlags.Public | BindingFlags.Instance)
                .Single();
            var constructorParams = constructor
                .GetParameters()
                .Select(pi => pi.ParameterType)
                .Select(t => this.serviceProvider.GetRequiredService(t))
                .ToArray();
            var instance = constructor.Invoke(constructorParams);

            return (DynamoDbSet<TEntity>)instance;
        }

then  in my context  I can dot this: 
    public Repository(XXDynamoContext context)
        {
            Db = context;
            DbSet = Db.Set<TEntity>();
        }

then it work well , 
but I am not sure It is the best way to do this ,
if so  ,can you add to this project ?

**Comment by jovi-Li** [comment]
sorry  , it should be :        DbSet = Db.Set  <  TEntity  > ();

**Comment by msotiroff** [comment]
@jovi-Li, if you just want to wrap the entity set in a generic repository, you don't need to change DynamoContext class and you cannot if you use the nuget package dependency.

You can create your repository like that:
```
public class Repository<TEntity> : IRepository<TEntity> where TEntity : class, new()
{
    private readonly DynamoDbSet<TEntity> dynamoDbSet;

    public Repository(DynamoDbSet<TEntity> dynamoDbSet)
    {
        this.dynamoDbSet = dynamoDbSet;
    }

    public async Task AddAsync(TEntity entity)
    {
        await this.dynamoDbSet.AddAsync(entity);
    }

    // ... Whatever CRUD operation you want.
}
```

Then for greater purity you can implement an extension method for adding a repository to your DI container like that:

```
public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddRepository<TContext, TEntity>(
        this IServiceCollection services,
        Expression<Func<TContext, DynamoDbSet<TEntity>>> dynamoDbSetExpression)
        where TEntity : class, new()
        where TContext : DynamoContext
    {
        services.AddTransient(sp => dynamoDbSetExpression
            .Compile()
            .Invoke(sp.GetRequiredService<TContext>()));

        services.AddTransient<IRepository<TEntity>, Repository<TEntity>>();

        return services;
    }
}
```

... and finally in your Startup.cs add whatever generic repository you want to the DI container:

```
public void ConfigureServices(IServiceCollection services)
{
    services
        .AddDynamoContext<BlogDbContext>(this.Configuration)
        .AddRepository<BlogDbContext, Article>(blog => blog.Articles)
        .AddRepository<BlogDbContext, Author>(blog => blog.Authors);
}
```

May be it's a good idea to make some abstractions for DynamoDbSet and DynamoContext in the next version in order to be easily mocked for testing.
