### ISSUE TITLE
type of List<string> when add got error 

### ISSUE THREAD

**Issue by jovi-Li** [msotiroff/EasyDynamo#6]
public class A
{
 public List<string> List{get;set;}
}
A a= new A();
account.List.Add("value1");
account.List.Add("value1");

when  DbSet.AddAsync(a)  will got error :
One or more parameter values were invalid: Input collection XXX contains duplicates 

in DynamoDbSet.cs  at line 47,
Add this code  can fix it ：

  this.operationConfig = new DynamoDBOperationConfig
            {
                OverrideTableName = tableNameExtractor.ExtractTableName<TEntity>(this.table),
               //set version
                Conversion = DynamoDBEntryConversion.V2
            };

can you  merge it ? or have other way ?

**Comment by msotiroff** [comment]
@jovi-Li, thanks for reporting this issue.
In version 1.0.4 you can configure the entry conversion version in the OnConfiguring method of your context class:
```
protected override void OnConfiguring(
        DynamoContextOptionsBuilder builder, IConfiguration configuration)
    {
        builder.UseEntryConversionV2();

        base.OnConfiguring(builder, configuration);
    }
```
... or in your Startup.cs:
```
services.AddDynamoContext<BlogDbContext>(
    this.Configuration,
    options => 
    {
        options.Conversion = DynamoDBEntryConversion.V2;
    });
```

If you don't specify the V2 conversion, the default one stays V1.
